version: '3.8'

services:
  coursematerial:
    image: einoob/pipeline-test
    ports:
      - 4000:80
    container_name: coursematerial
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
